# Created June 2020; F.P.A. Vogt; frederic.vogt@alumni.anu.edu.au
# Adapted September 2020; F.P.A. Vogt; frederic.vogt@alumni.anu.edu.au

name: CI_docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  docs:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      # Checkout our repository
      - uses: actions/checkout@v2

      # Set up Python
      - uses: actions/setup-python@v1

      # Install any dependency we require
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx-rtd-theme
        shell: bash

      # Launch a home-made python script to compile and check the docs.
      - name: Compile the docs and look for errors/warnings
        run: |
          python .github/workflows/docs_check.py

        shell: bash
